[package]
name = "cellular"
version = "0.1.0"
authors = ["Zotho <svjatoslavalekseef2@gmail.com>"]
edition = "2018"

[dependencies]
macroquad = { git="https://github.com/not-fl3/macroquad", rev = "32bb775" }